### ISSUE TITLE
README about programatically toggle the menu isn't correct

### ISSUE THREAD

**Issue by d10sfan** [godot-extended-libraries/godot-debug-menu#15]
Using the latest in the master branch, the toggle code examples don't work (https://github.com/godot-extended-libraries/godot-debug-menu#usage).

If I do that, I get errors that the Canvas does not have those properties.

If I instead do this:

```gdscript
var debug_menu = DebugMenu.get_node("DebugMenu")
debug_menu.style = debug_menu.Style.VISIBLE_COMPACT
```

Then as well the NONE should be HIDDEN instead

```gdscript
var debug_menu = DebugMenu.get_node("DebugMenu")
debug_menu.style = debug_menu.Style.HIDDEN
```

I'm not sure if this is expected behavior or not, if it is I could open a PR for some README changes.

**Comment by Calinou** [comment]
This was likely changed by https://github.com/godot-extended-libraries/godot-debug-menu/commit/2d1bf27e5901186080e0fde5adc56df65dd9c583.

The correct fix is to put the script on the CanvasLayer instead of a child Control node, so that you can set properties directly on `DebugMenu` instead of having to use `get_node()`. Feel free to open a pull request for this :slightly_smiling_face:

**Comment by d10sfan** [comment]
Ah gotcha, I'll see if I can make that work locally and if so provide a PR soon.

**Comment by d10sfan** [comment]
Created a PR in https://github.com/godot-extended-libraries/godot-debug-menu/pull/16
